name: my first workflow
on: push 
jobs:
    First_job_with_actions: 
        runs-on: ubuntu-latest
        steps: 
        - name: clone the repo
          uses: actions/checkout@v6
        - name: List and read the file
          run: | 
            echo "My first github actions"
            ################################
            ls -altr
            ################################
            cat README.md
            ################################
        #- name: Generate Art ASCII work
        
      #run: cowsay -f king "King diagram" >> King.txt

        #- name: list files
        #  run: ls -altr

        #- name: read files
        #  run: cat README.md
        
          