name: my first workflow
on: push 
jobs:
    First_job with actions: 
        runs-on: ubuntu-latest
        steps: 
        - name: clone the repo
          uses: actions/checkout@v6
        - name: welocme mesage
          run: echo "My first github actions"

        - name: list files
          run: ls -altr

        - name: read files
          run: cat README.md
        
          