name: Generate ASCII
on: push 
jobs:
  Build_Job1:
    runs-on: ubuntu-latest
    steps:
    - name: Install Cowsay program
      run: sudo apt-get install cowsay
        
    - name: Execute Cowsay CMD
      run: cowsay -f dragon "Run cover Iam dragon" >> dragon.txt
  Test_Job2:
    runs-on: ubuntu-latest
    steps:
    - name: sleep for 10 secs
      run: sleep 10

    - name: test file exists
      run: grep -i "dragon" dragon.txt

  Deploy_Job3:
    runs-on: ubuntu-latest
    steps:
    - name: Read File
      run: cat dragon.txt
     
      