name: Generate ASCII
on: push 
jobs:
    ASCII_Job: 
        runs-on: ubuntu-latest
        steps: 
        - name: clone the repo
          uses: actions/checkout@v6

        - name: list the repo files
          run: ls -altr
          
        - name: Executeshell
          run: |
          chmod +X shell.sh
          ls -altr
          ./shell.sh
        

       