name: Generate ASCII
on: push 
jobs:
  Build_Job1:
    runs-on: ubuntu-latest
    steps:
    - name: Install Cowsay program
      run: sudo apt-get install cowsay
        
    - name: Execute Cowsay CMD
      run: cowsay -f dragon "Run cover Iam dragon" >> dragon.txt
    - name: Upload dragon text file
      uses: actions/upload-artifact@v6
      with:
          name: dragon-text-file
          path: dragon.txt
  

  Test_Job2:
    needs: Build_Job1
    runs-on: ubuntu-latest
    steps:
    - name: download dragon text file
      uses: actions/download-artifact@v6
      with:
        name: dragon-text-file

    - name: test file exists
      run: grep -i "dragon" dragon.txt

  Deploy_Job3:
    needs: Test_Job2
    runs-on: ubuntu-latest
    steps:
    - name: download dragon text file
      uses: actions/download-artifact@v6
      with:
        name: dragon-text-file 

    - name: Read File
      run: cat dragon.txt
  # comment   
      